---
eureka:
  instance:
    instance-id: eureka-client1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  profiles: peer2
  application:
    name: eureka-client

---
eureka:
  instance:
    instance-id: eureka-client2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  profiles: peer1
  application:
    name: eureka-client